"""not initial migration

Revision ID: 4f5b80751ff0
Revises: 49c3f3abbe91
Create Date: 2024-02-05 23:05:20.280251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5b80751ff0'
down_revision = '49c3f3abbe91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('reservations', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
#         batch_op.alter_column('user_id',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#         batch_op.alter_column('reserved_car_id',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#         batch_op.create_foreign_key(None, 'owner', ['owner_id'], ['id'])



       with op.batch_alter_table('reservations', schema=None) as batch_op:
              batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
              batch_op.alter_column('user_id',
                     existing_type=sa.INTEGER(),
                     nullable=False)
              batch_op.alter_column('reserved_car_id',
                     existing_type=sa.INTEGER(),
                     nullable=False)
              batch_op.create_foreign_key('fk_reservations_owner_id', 'owner', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reserved_car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
