"""empty message

Revision ID: 90e97829b6f5
Revises: 1f56eeb9272b
Create Date: 2024-01-16 21:36:45.561529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e97829b6f5'
down_revision = '1f56eeb9272b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.String(), nullable=False))
        batch_op.drop_column('additional_information')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_information', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###
