"""fixing database conflict

Revision ID: 940f3a25f3c2
Revises: 8e220168910a
Create Date: 2024-03-10 11:11:19.613596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940f3a25f3c2'
down_revision = '8e220168910a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_timestamp')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('reset_token_timestamp')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
