"""added token column

Revision ID: a128ba05f35d
Revises: fa460f9ae0a2
Create Date: 2024-02-25 22:57:41.310336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a128ba05f35d'
down_revision = 'fa460f9ae0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_timestamp')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('reset_token_timestamp')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
