"""Add reset_token_timestamp column to User and Owner models

Revision ID: b83625217064
Revises: 33c42482b9e4
Create Date: 2024-02-21 16:50:55.474450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83625217064'
down_revision = '33c42482b9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_timestamp')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('reset_token_timestamp')

    # ### end Alembic commands ###
